source 'https://gitlab.com/novapps/ios-app/framework/private-cocoapods-spec-repo.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'NOVAppReview_Example' do
  pod 'NOVAppReview', :path => '../'
end
