# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://gitlab.com/novapps/ios-app/framework/private-cocoapods-spec-repo.git'
source 'https://cdn.cocoapods.org/'

target 'NOVAppReview-OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NOVAppReview-OC
  pod 'NOVAppReview', :path => '../'
  pod 'AFNetworking'

end
